package(default_visibility = ["//visibility:public"])

filegroup(
    name = "graphdb-se",
    srcs = [
        "auto-upgrade.sh",
        "dump-repository.sh",
        "empty-repository.sh",
        "upload-repository.sh"
    ]
)