"""Exposes image coordinates declared in MODULE.bazel to BUILD files.

BUILD files cannot `load()` from MODULE.bazel, so this module extension takes
the coordinates declared there (via the `image_versions.fuseki(...)` tag) and
generates a small `@dsp_image_versions//:defs.bzl` that BUILD files load. This
keeps MODULE.bazel the single source of truth for the Fuseki image tag, which is
consumed by both modules/fuseki/BUILD.bazel (image labels/env/repo_tags) and
modules/webapi buildinfo (the /version report).

(sipi needs no entry here: its version is extracted from the pulled base image's
OCI label — see //tools/buildinfo oci_config_label — so the MODULE.bazel digest
stays its sole source.)
"""

def _defs_repo_impl(rctx):
    tag = rctx.attr.fuseki_image.rsplit(":", 1)[-1]
    rctx.file("BUILD.bazel", "exports_files([\"defs.bzl\"])\n")
    rctx.file(
        "defs.bzl",
        "\n".join([
            "# Generated by //tools/image_versions — do not edit.",
            "FUSEKI_IMAGE = \"%s\"" % rctx.attr.fuseki_image,
            "FUSEKI_IMAGE_TAG = \"%s\"" % tag,
            "FUSEKI_DIST_VERSION = \"%s\"" % rctx.attr.fuseki_dist_version,
            "",
        ]),
    )

_defs_repo = repository_rule(
    implementation = _defs_repo_impl,
    attrs = {
        "fuseki_image": attr.string(mandatory = True),
        "fuseki_dist_version": attr.string(mandatory = True),
    },
)

def _image_versions_impl(mctx):
    fuseki_image = None
    fuseki_dist_version = None
    for mod in mctx.modules:
        for f in mod.tags.fuseki:
            fuseki_image = f.image
            fuseki_dist_version = f.dist_version
    if fuseki_image == None:
        fail("image_versions extension: no image_versions.fuseki(...) tag declared")
    _defs_repo(
        name = "dsp_image_versions",
        fuseki_image = fuseki_image,
        fuseki_dist_version = fuseki_dist_version,
    )

image_versions = module_extension(
    implementation = _image_versions_impl,
    tag_classes = {
        "fuseki": tag_class(attrs = {
            "image": attr.string(mandatory = True, doc = "Full daschswiss/apache-jena-fuseki:<tag>"),
            "dist_version": attr.string(mandatory = True, doc = "Upstream Jena dist version (no build suffix)"),
        }),
    },
)
