"""Exposes the Fuseki dist (jar) version declared in MODULE.bazel to BUILD files.

BUILD files cannot `load()` from MODULE.bazel, so this module extension takes the
`FUSEKI_DIST_VERSION` declared there (via the `image_versions.fuseki(...)` tag)
and generates a small `@dsp_image_versions//:defs.bzl` that BUILD files load. It
is consumed by modules/fuseki/BUILD.bazel (image env: FUSEKI_VERSION + the OTLP
service.version resource attribute) and modules/webapi buildinfo (the /version
report). The Fuseki *image* tag is NOT here — the image is versioned by
release-please (git version, stamped into the image label), like knora-api.

(sipi needs no entry here: its version is extracted from the pulled base image's
OCI label — see //tools/buildinfo oci_config_label — so the MODULE.bazel digest
stays its sole source.)
"""

def _defs_repo_impl(rctx):
    rctx.file("BUILD.bazel", "exports_files([\"defs.bzl\"])\n")
    rctx.file(
        "defs.bzl",
        "\n".join([
            "# Generated by //tools/image_versions — do not edit.",
            "FUSEKI_DIST_VERSION = \"%s\"" % rctx.attr.fuseki_dist_version,
            "",
        ]),
    )

_defs_repo = repository_rule(
    implementation = _defs_repo_impl,
    attrs = {
        "fuseki_dist_version": attr.string(mandatory = True),
    },
)

def _image_versions_impl(mctx):
    fuseki_dist_version = None
    for mod in mctx.modules:
        for f in mod.tags.fuseki:
            fuseki_dist_version = f.dist_version
    if fuseki_dist_version == None:
        fail("image_versions extension: no image_versions.fuseki(...) tag declared")
    _defs_repo(
        name = "dsp_image_versions",
        fuseki_dist_version = fuseki_dist_version,
    )

image_versions = module_extension(
    implementation = _image_versions_impl,
    tag_classes = {
        "fuseki": tag_class(attrs = {
            "dist_version": attr.string(mandatory = True, doc = "Upstream Jena dist version (no build suffix)"),
        }),
    },
)
