FROM dhlabbasel/sbt-ivy2-cache

MAINTAINER Ivan Subotic "ivan.subotic@unibas.ch"

# copy source code
RUN mkdir /src
COPY . /src

# generate deployment jars and clean up
RUN \
  cd /src && \
  sbt stage && \
  mkdir /salsah && \
  cp -r /src/target/universal/stage/* /salsah

# Expose the webapi default port
EXPOSE 3335