openapi: 3.1.0
info:
  title: dsp-ingest-projects
  version: v0.5.0-23-gcbbe7a6-dirty
servers:
- url: http://localhost:3340
  description: Local development server
- url: https://ingest.dev.dasch.swiss
  description: Production server
paths:
  /projects:
    get:
      tags:
      - projects
      operationId: getProjects
      responses:
        '200':
          description: ''
          headers:
            Content-Range:
              required: true
              schema:
                type: string
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProjectResponse'
        '400':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        '401':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unauthorized'
        '404':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'
        '500':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
        '503':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unhealthy'
      security:
      - httpAuth: []
  /projects/{shortcode}:
    get:
      tags:
      - projects
      operationId: getProjectsShortcode
      parameters:
      - name: shortcode
        in: path
        description: The shortcode of the project must be an exactly 4 characters
          long hexadecimal string.
        required: true
        schema:
          type: string
          pattern: ^\p{XDigit}{4,4}$
        example: '0001'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectResponse'
        '400':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        '401':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unauthorized'
        '404':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'
        '500':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
        '503':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unhealthy'
      security:
      - httpAuth: []
  /projects/{shortcode}/checksumreport:
    get:
      tags:
      - projects
      operationId: getProjectsShortcodeChecksumreport
      parameters:
      - name: shortcode
        in: path
        description: The shortcode of the project must be an exactly 4 characters
          long hexadecimal string.
        required: true
        schema:
          type: string
          pattern: ^\p{XDigit}{4,4}$
        example: '0001'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssetCheckResultResponse'
        '400':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        '401':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unauthorized'
        '404':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'
        '500':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
        '503':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unhealthy'
      security:
      - httpAuth: []
  /projects/{shortcode}/assets/{assetId}:
    get:
      tags:
      - assets
      operationId: getProjectsShortcodeAssetsAssetid
      parameters:
      - name: shortcode
        in: path
        description: The shortcode of the project must be an exactly 4 characters
          long hexadecimal string.
        required: true
        schema:
          type: string
          pattern: ^\p{XDigit}{4,4}$
        example: '0001'
      - name: assetId
        in: path
        required: true
        schema:
          type: string
          pattern: ^[a-zA-Z0-9-_]{4,}$
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssetInfoResponse'
        '400':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        '401':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unauthorized'
        '404':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'
        '500':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
        '503':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unhealthy'
      security:
      - httpAuth: []
  /projects/{shortcode}/bulk-ingest:
    post:
      tags:
      - bulk-ingest
      description: Triggers an ingest on the project with the given shortcode. Currently
        only supports ingest of images. The files are expected to be in the `tmp/<project_shortcode>`
        directory.
      operationId: postProjectsShortcodeBulk-ingest
      parameters:
      - name: shortcode
        in: path
        description: The shortcode of the project must be an exactly 4 characters
          long hexadecimal string.
        required: true
        schema:
          type: string
          pattern: ^\p{XDigit}{4,4}$
        example: '0001'
      responses:
        '202':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectResponse'
              example:
                id: '0001'
        '400':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        '401':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unauthorized'
        '404':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'
        '500':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
        '503':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unhealthy'
      security:
      - httpAuth: []
  /projects/{shortcode}/bulk-ingest/finalize:
    post:
      tags:
      - bulk-ingest
      description: Finalizes the bulk ingest. This will remove the files from the
        `tmp/<project_shortcode>` directory and the directory itself. This will remove
        also the mapping.csv file.
      operationId: postProjectsShortcodeBulk-ingestFinalize
      parameters:
      - name: shortcode
        in: path
        description: The shortcode of the project must be an exactly 4 characters
          long hexadecimal string.
        required: true
        schema:
          type: string
          pattern: ^\p{XDigit}{4,4}$
        example: '0001'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectResponse'
              example:
                id: '0001'
        '400':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        '401':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unauthorized'
        '404':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'
        '500':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
        '503':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unhealthy'
      security:
      - httpAuth: []
  /projects/{shortcode}/bulk-ingest/mapping.csv:
    get:
      tags:
      - bulk-ingest
      description: 'Get the current result of the bulk ingest, may be incomplete.
        The result is a csv with the following structure: original,derivative'
      operationId: getProjectsShortcodeBulk-ingestMapping.csv
      parameters:
      - name: shortcode
        in: path
        description: The shortcode of the project must be an exactly 4 characters
          long hexadecimal string.
        required: true
        schema:
          type: string
          pattern: ^\p{XDigit}{4,4}$
        example: '0001'
      responses:
        '200':
          description: ''
          headers:
            Content-Type:
              required: true
              schema:
                type: string
          content:
            text/csv:
              schema:
                type: string
        '400':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        '401':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unauthorized'
        '404':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'
        '500':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
        '503':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unhealthy'
      security:
      - httpAuth: []
  /projects/{shortcode}/export:
    post:
      tags:
      - import/export
      operationId: postProjectsShortcodeExport
      parameters:
      - name: shortcode
        in: path
        description: The shortcode of the project must be an exactly 4 characters
          long hexadecimal string.
        required: true
        schema:
          type: string
          pattern: ^\p{XDigit}{4,4}$
        example: '0001'
      responses:
        '200':
          description: ''
          headers:
            Content-Disposition:
              required: true
              schema:
                type: string
            Content-Type:
              required: true
              schema:
                type: string
          content:
            application/zip:
              schema:
                type: string
                format: binary
        '400':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        '401':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unauthorized'
        '404':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'
        '500':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
        '503':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unhealthy'
      security:
      - httpAuth: []
  /projects/{shortcode}/import:
    get:
      tags:
      - import/export
      operationId: getProjectsShortcodeImport
      parameters:
      - name: shortcode
        in: path
        description: The shortcode of the project must be an exactly 4 characters
          long hexadecimal string.
        required: true
        schema:
          type: string
          pattern: ^\p{XDigit}{4,4}$
        example: '0001'
      - name: Content-Type
        in: header
        required: true
        schema:
          type: string
        example: application/zip
      requestBody:
        content:
          application/zip:
            schema:
              type: string
              format: binary
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UploadResponse'
        '400':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        '401':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unauthorized'
        '404':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'
        '500':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
        '503':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unhealthy'
      security:
      - httpAuth: []
components:
  schemas:
    Argument:
      required:
      - argument
      - reason
      type: object
      properties:
        argument:
          type: string
        reason:
          type: string
    AssetCheckResultEntry:
      required:
      - assetId
      - originalFilename
      type: object
      properties:
        assetId:
          type: string
        originalFilename:
          type: string
        results:
          type: array
          items:
            $ref: '#/components/schemas/SingleFileCheckResultResponse'
    AssetCheckResultResponse:
      required:
      - summary
      type: object
      properties:
        summary:
          $ref: '#/components/schemas/AssetCheckResultSummary'
        results:
          type: array
          items:
            $ref: '#/components/schemas/AssetCheckResultEntry'
    AssetCheckResultSummary:
      required:
      - numberOfAssets
      - numberOfFiles
      - numberOfChecksumMatches
      type: object
      properties:
        numberOfAssets:
          type: integer
          format: int32
        numberOfFiles:
          type: integer
          format: int32
        numberOfChecksumMatches:
          type: integer
          format: int32
    AssetInfoResponse:
      required:
      - internalFilename
      - originalInternalFilename
      - originalFilename
      - checksumOriginal
      - checksumDerivative
      type: object
      properties:
        internalFilename:
          type: string
        originalInternalFilename:
          type: string
        originalFilename:
          type: string
        checksumOriginal:
          type: string
        checksumDerivative:
          type: string
        width:
          type: integer
          format: int32
        height:
          type: integer
          format: int32
        duration:
          type: number
          format: double
        fps:
          type: number
          format: double
        internalMimeType:
          type: string
        originalMimeType:
          type: string
    BadRequest:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Argument'
    DOWN:
      type: object
    InternalServerError:
      required:
      - errorMessage
      type: object
      properties:
        errorMessage:
          type: string
    NotFound:
      required:
      - id
      - type
      type: object
      properties:
        id:
          type: string
        type:
          type: string
    ProjectResponse:
      required:
      - id
      type: object
      properties:
        id:
          type: string
    SingleFileCheckResultResponse:
      required:
      - filename
      - checksumMatches
      type: object
      properties:
        filename:
          type: string
        checksumMatches:
          type: boolean
    Status:
      oneOf:
      - $ref: '#/components/schemas/DOWN'
      - $ref: '#/components/schemas/UP'
    UP:
      type: object
    Unauthorized:
      required:
      - reason
      type: object
      properties:
        reason:
          type: string
    Unhealthy:
      required:
      - status
      type: object
      properties:
        status:
          $ref: '#/components/schemas/Status'
    UploadResponse:
      required:
      - status
      type: object
      properties:
        status:
          type: string
  securitySchemes:
    httpAuth:
      type: http
      scheme: bearer
