openapi: 3.1.0
info:
  title: dsp-ingest-monitoring
  version: v0.5.0-23-gcbbe7a6-dirty
servers:
- url: http://localhost:3340
  description: Local development server
- url: https://ingest.dev.dasch.swiss
  description: Production server
paths:
  /info:
    get:
      tags:
      - monitoring
      operationId: getInfo
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InfoEndpointResponse'
              example:
                name: dsp-ingest
                version: v0.5.0-23-gcbbe7a6-dirty
                scalaVersion: 3.3.1
                sbtVersion: 1.9.8
                buildTime: 2024-01-10 19:39:26.411+0100
                gitCommit: cbbe7a6a06ba9dc64a6939ceb7880015a4c3fa9b
        '400':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        '401':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unauthorized'
        '404':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'
        '500':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
        '503':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unhealthy'
  /health:
    get:
      tags:
      - monitoring
      operationId: getHealth
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Health'
              example:
                status: UP
        '400':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        '401':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unauthorized'
        '404':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'
        '500':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
        '503':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unhealthy'
  /metrics:
    get:
      tags:
      - monitoring
      operationId: getMetrics
      responses:
        '200':
          description: ''
          content:
            text/plain:
              schema:
                type: string
        '400':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        '401':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unauthorized'
        '404':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'
        '500':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
        '503':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unhealthy'
components:
  schemas:
    Argument:
      required:
      - argument
      - reason
      type: object
      properties:
        argument:
          type: string
        reason:
          type: string
    BadRequest:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Argument'
    DOWN:
      type: object
    Health:
      required:
      - status
      type: object
      properties:
        status:
          $ref: '#/components/schemas/Status'
    InfoEndpointResponse:
      required:
      - name
      - version
      - scalaVersion
      - sbtVersion
      - buildTime
      - gitCommit
      type: object
      properties:
        name:
          type: string
        version:
          type: string
        scalaVersion:
          type: string
        sbtVersion:
          type: string
        buildTime:
          type: string
        gitCommit:
          type: string
    InternalServerError:
      required:
      - errorMessage
      type: object
      properties:
        errorMessage:
          type: string
    NotFound:
      required:
      - id
      - type
      type: object
      properties:
        id:
          type: string
        type:
          type: string
    Status:
      oneOf:
      - $ref: '#/components/schemas/DOWN'
      - $ref: '#/components/schemas/UP'
    UP:
      type: object
    Unauthorized:
      required:
      - reason
      type: object
      properties:
        reason:
          type: string
    Unhealthy:
      required:
      - status
      type: object
      properties:
        status:
          $ref: '#/components/schemas/Status'
