---

# Config file for https://github.com/igorshubovych/markdownlint-cli

# MD007/ul-indent - Unordered list indentation
MD007: 
    # Whether to indent the first level of the list
    start_indented: false
    # By how many spaces every next level must be indented. The default of 2 is not compatible with mkdocs!
    indent: 4

# MD009/no-trailing-spaces - Trailing spaces
MD009: false

# MD012/no-multiple-blanks - Multiple consecutive blank lines
MD012: false

# MD013/line-length - Line length
MD013: 
    line_length: 120
    heading_line_length: 120
    code_block_line_length: 120
    # Include code blocks
    code_blocks: true
    # Include tables
    tables: false
    # Include headings
    headings: true
    headers: true
    # Strict length checking
    strict: false
    # Stern length checking
    stern: false

# MD033/no-inline-html - Inline HTML
MD033: 
    allowed_elements: [br, center]

# MD041/first-line-heading/first-line-h1 - First line in a file should be a top-level heading
MD041: false

# MD045/no-alt-text - Images should have alternate text (alt text)
MD045: false
