buildozer 'remove deps @maven//:com_google_errorprone_error_prone_annotations' //salsah1:main_library
buildozer 'remove deps @maven//:org_eclipse_rdf4j_rdf4j_repository_event' //salsah1:main_library
buildozer 'remove deps @maven//:net_sf_saxon_Saxon_HE' //salsah1:main_library
buildozer 'remove deps @maven//:org_slf4j_slf4j_api' //salsah1:main_library
buildozer 'remove deps @maven//:org_springframework_spring_core' //salsah1:main_library
buildozer 'remove deps @maven//:org_apache_thrift_libthrift' //salsah1:main_library
buildozer 'remove deps @maven//:io_kamon_kamon_instrumentation_common_2_12' //salsah1:main_library
buildozer 'remove deps @maven//:org_eclipse_rdf4j_rdf4j_model' //salsah1:main_library
buildozer 'remove deps @maven//:org_bouncycastle_bcpkix_jdk15on' //salsah1:main_library
buildozer 'remove deps @maven//:com_jsuereth_scala_arm_2_12' //salsah1:main_library
buildozer 'remove deps @maven//:org_mapdb_mapdb' //salsah1:main_library
buildozer 'remove deps @maven//:org_eclipse_rdf4j_rdf4j_queryresultio_text' //salsah1:main_library
buildozer 'remove deps @maven//:com_typesafe_akka_akka_slf4j_2_12' //salsah1:main_library
buildozer 'remove deps @maven//:io_netty_netty_tcnative_boringssl_static' //salsah1:main_library
buildozer 'remove deps @maven//:org_eclipse_rdf4j_rdf4j_queryparser_serql' //salsah1:main_library
buildozer 'remove deps @maven//:io_netty_netty_resolver_dns' //salsah1:main_library
buildozer 'remove deps @maven//:org_eclipse_rdf4j_rdf4j_repository_dataset' //salsah1:main_library
buildozer 'remove deps @maven//:org_json4s_json4s_jackson_2_12' //salsah1:main_library
buildozer 'remove deps @maven//:org_eclipse_rdf4j_rdf4j_queryparser_api' //salsah1:main_library
buildozer 'remove deps @maven//:org_springframework_security_spring_security_core' //salsah1:main_library
buildozer 'remove deps @maven//:org_eclipse_rdf4j_rdf4j_http_client' //salsah1:main_library
buildozer 'remove deps @maven//:taglibs_standard' //salsah1:main_library
buildozer 'remove deps @maven//:javax_servlet_jstl' //salsah1:main_library
buildozer 'remove deps @maven//:org_springframework_spring_web' //salsah1:main_library
buildozer 'remove deps @maven//:com_thoughtworks_paranamer_paranamer' //salsah1:main_library
buildozer 'remove deps @maven//:javax_ws_rs_jsr311_api' //salsah1:main_library
buildozer 'remove deps @maven//:com_pauldijou_jwt_json_common_2_12' //salsah1:main_library
buildozer 'remove deps @maven//:com_github_andrewoma_dexx_collection' //salsah1:main_library
buildozer 'remove deps @maven//:org_springframework_spring_expression' //salsah1:main_library
buildozer 'remove deps @maven//:io_gatling_highcharts_gatling_charts_highcharts' //salsah1:main_library
buildozer 'remove deps @maven//:io_netty_netty_transport_native_unix_common' //salsah1:main_library
buildozer 'remove deps @maven//:org_eclipse_rdf4j_rdf4j_rio_trig' //salsah1:main_library
buildozer 'remove deps @maven//:io_swagger_swagger_jaxrs' //salsah1:main_library
buildozer 'remove deps @maven//:org_eclipse_rdf4j_rdf4j_lucene_spin' //salsah1:main_library
buildozer 'remove deps @maven//:org_eclipse_rdf4j_rdf4j_sail_api' //salsah1:main_library
buildozer 'remove deps @maven//:org_apache_httpcomponents_fluent_hc' //salsah1:main_library
buildozer 'remove deps @maven//:org_apache_lucene_lucene_sandbox' //salsah1:main_library
buildozer 'remove deps @maven//:com_pauldijou_jwt_spray_json_2_12' //salsah1:main_library
buildozer 'remove deps @maven//:org_eclipse_rdf4j_rdf4j_sail_spin' //salsah1:main_library
buildozer 'remove deps @maven//:commons_collections_commons_collections' //salsah1:main_library
buildozer 'remove deps @maven//:com_ibm_icu_icu4j' //salsah1:main_library
buildozer 'remove deps @maven//:org_apache_lucene_lucene_highlighter' //salsah1:main_library
buildozer 'remove deps @maven//:org_eclipse_rdf4j_rdf4j_config' //salsah1:main_library
buildozer 'remove deps @maven//:xerces_xercesImpl' //salsah1:main_library
buildozer 'remove deps @maven//:org_eclipse_rdf4j_rdf4j_sail_lucene_api' //salsah1:main_library
buildozer 'remove deps @maven//:org_simpleflatmapper_lightning_csv' //salsah1:main_library
buildozer 'remove deps @maven//:com_softwaremill_quicklens_quicklens_2_12' //salsah1:main_library
buildozer 'remove deps @maven//:commons_io_commons_io' //salsah1:main_library
buildozer 'remove deps @maven//:com_fasterxml_jackson_dataformat_jackson_dataformat_yaml' //salsah1:main_library
buildozer 'remove deps @maven//:io_gatling_gatling_app' //salsah1:main_library
buildozer 'remove deps @maven//:com_google_guava_guava' //salsah1:main_library
buildozer 'remove deps @maven//:org_scala_stm_scala_stm_2_12' //salsah1:main_library
buildozer 'remove deps @maven//:org_apache_httpcomponents_httpcore_nio' //salsah1:main_library
buildozer 'remove deps @maven//:com_typesafe_ssl_config_core_2_12' //salsah1:main_library
buildozer 'remove deps @maven//:com_sun_activation_javax_activation' //salsah1:main_library
buildozer 'remove deps @maven//:org_noggit_noggit' //salsah1:main_library
buildozer 'remove deps @maven//:org_jodd_jodd_core' //salsah1:main_library
buildozer 'remove deps @maven//:org_reflections_reflections' //salsah1:main_library
buildozer 'remove deps @maven//:org_rogach_scallop_2_12' //salsah1:main_library
buildozer 'remove deps @maven//:de_heikoseeberger_akka_http_circe_2_12' //salsah1:main_library
buildozer 'remove deps @maven//:commons_cli_commons_cli' //salsah1:main_library
buildozer 'remove deps @maven//:org_eclipse_rdf4j_rdf4j_query' //salsah1:main_library
buildozer 'remove deps @maven//:org_eclipse_rdf4j_rdf4j_rio_nquads' //salsah1:main_library
buildozer 'remove deps @maven//:org_locationtech_spatial4j_spatial4j' //salsah1:main_library
buildozer 'remove deps @maven//:org_eclipse_rdf4j_rdf4j_rio_rdfjson' //salsah1:main_library
buildozer 'remove deps @maven//:org_typelevel_cats_macros_2_12' //salsah1:main_library
buildozer 'remove deps @maven//:io_swagger_swagger_core' //salsah1:main_library
buildozer 'remove deps @maven//:org_spire_math_jawn_parser_2_12' //salsah1:main_library
