buildozer 'remove deps @maven//:org_checkerframework_checker_qual' //salsah1/src/test/scala/org.knora.salsah/browser:InternationalizationSpec
buildozer 'remove deps @maven//:io_gatling_gatling_http_client' //salsah1/src/test/scala/org.knora.salsah/browser:InternationalizationSpec
buildozer 'remove deps @maven//:io_kamon_kamon_instrumentation_common_2_12' //salsah1/src/test/scala/org.knora.salsah/browser:InternationalizationSpec
buildozer 'remove deps @maven//:org_rogach_scallop_2_12' //salsah1/src/test/scala/org.knora.salsah/browser:InternationalizationSpec
buildozer 'remove deps @maven//:org_apache_lucene_lucene_analyzers_common' //salsah1/src/test/scala/org.knora.salsah/browser:InternationalizationSpec
buildozer 'remove deps @maven//:org_apache_solr_solr_solrj' //salsah1/src/test/scala/org.knora.salsah/browser:InternationalizationSpec
buildozer 'remove deps @maven//:taglibs_standard' //salsah1/src/test/scala/org.knora.salsah/browser:InternationalizationSpec
buildozer 'remove deps @maven//:io_swagger_swagger_core' //salsah1/src/test/scala/org.knora.salsah/browser:InternationalizationSpec
buildozer 'remove deps @maven//:com_tdunning_t_digest' //salsah1/src/test/scala/org.knora.salsah/browser:InternationalizationSpec
buildozer 'remove deps @maven//:ch_qos_logback_logback_core' //salsah1/src/test/scala/org.knora.salsah/browser:InternationalizationSpec
buildozer 'remove deps @maven//:io_netty_netty_transport_native_unix_common' //salsah1/src/test/scala/org.knora.salsah/browser:InternationalizationSpec
buildozer 'remove deps @maven//:org_eclipse_rdf4j_rdf4j_rio_nquads' //salsah1/src/test/scala/org.knora.salsah/browser:InternationalizationSpec
buildozer 'remove deps @maven//:javax_ws_rs_jsr311_api' //salsah1/src/test/scala/org.knora.salsah/browser:InternationalizationSpec
buildozer 'remove deps @maven//:org_eclipse_rdf4j_rdf4j_rio_jsonld' //salsah1/src/test/scala/org.knora.salsah/browser:InternationalizationSpec
buildozer 'remove deps @maven//:org_eclipse_rdf4j_rdf4j_rio_ntriples' //salsah1/src/test/scala/org.knora.salsah/browser:InternationalizationSpec
buildozer 'remove deps @maven//:org_eclipse_rdf4j_rdf4j_storage' //salsah1/src/test/scala/org.knora.salsah/browser:InternationalizationSpec
buildozer 'remove deps @maven//:commons_digester_commons_digester' //salsah1/src/test/scala/org.knora.salsah/browser:InternationalizationSpec
buildozer 'remove deps @maven//:io_netty_netty_common' //salsah1/src/test/scala/org.knora.salsah/browser:InternationalizationSpec
buildozer 'remove deps @maven//:io_netty_netty_transport' //salsah1/src/test/scala/org.knora.salsah/browser:InternationalizationSpec
buildozer 'remove deps @maven//:org_eclipse_rdf4j_rdf4j_queryresultio_api' //salsah1/src/test/scala/org.knora.salsah/browser:InternationalizationSpec
buildozer 'remove deps @maven//:org_eclipse_rdf4j_rdf4j_sail_inferencer' //salsah1/src/test/scala/org.knora.salsah/browser:InternationalizationSpec
buildozer 'remove deps @maven//:io_netty_netty_transport_native_epoll_linux_x86_64' //salsah1/src/test/scala/org.knora.salsah/browser:InternationalizationSpec
buildozer 'remove deps @maven//:org_eclipse_rdf4j_rdf4j_sail_lucene_api' //salsah1/src/test/scala/org.knora.salsah/browser:InternationalizationSpec
buildozer 'remove deps @maven//:io_swagger_swagger_annotations' //salsah1/src/test/scala/org.knora.salsah/browser:InternationalizationSpec
buildozer 'remove deps @maven//:io_pebbletemplates_pebble' //salsah1/src/test/scala/org.knora.salsah/browser:InternationalizationSpec
buildozer 'remove deps @maven//:org_apache_httpcomponents_httpcore' //salsah1/src/test/scala/org.knora.salsah/browser:InternationalizationSpec
buildozer 'remove deps @maven//:org_apache_lucene_lucene_spatial3d' //salsah1/src/test/scala/org.knora.salsah/browser:InternationalizationSpec
buildozer 'remove deps @maven//:org_springframework_spring_context' //salsah1/src/test/scala/org.knora.salsah/browser:InternationalizationSpec
buildozer 'remove deps @maven//:com_thoughtworks_paranamer_paranamer' //salsah1/src/test/scala/org.knora.salsah/browser:InternationalizationSpec
buildozer 'remove deps @maven//:commons_codec_commons_codec' //salsah1/src/test/scala/org.knora.salsah/browser:InternationalizationSpec
buildozer 'remove deps @maven//:org_eclipse_rdf4j_rdf4j_sail_solr' //salsah1/src/test/scala/org.knora.salsah/browser:InternationalizationSpec
buildozer 'remove deps @maven//:org_eclipse_rdf4j_rdf4j_client' //salsah1/src/test/scala/org.knora.salsah/browser:InternationalizationSpec
buildozer 'remove deps @maven//:io_gatling_gatling_jdbc' //salsah1/src/test/scala/org.knora.salsah/browser:InternationalizationSpec
buildozer 'remove deps @maven//:io_netty_netty_codec_http' //salsah1/src/test/scala/org.knora.salsah/browser:InternationalizationSpec
buildozer 'remove deps @maven//:commons_io_commons_io' //salsah1/src/test/scala/org.knora.salsah/browser:InternationalizationSpec
buildozer 'remove deps @maven//:org_apache_lucene_lucene_spatial_extras' //salsah1/src/test/scala/org.knora.salsah/browser:InternationalizationSpec
buildozer 'remove deps @maven//:org_apache_jena_jena_rdfconnection' //salsah1/src/test/scala/org.knora.salsah/browser:InternationalizationSpec
buildozer 'remove deps @maven//:com_twitter_chill_2_12' //salsah1/src/test/scala/org.knora.salsah/browser:InternationalizationSpec
buildozer 'remove deps @maven//:org_eclipse_rdf4j_rdf4j_repository_dataset' //salsah1/src/test/scala/org.knora.salsah/browser:InternationalizationSpec
buildozer 'remove deps @maven//:org_eclipse_rdf4j_rdf4j_queryresultio_text' //salsah1/src/test/scala/org.knora.salsah/browser:InternationalizationSpec
buildozer 'remove deps @maven//:org_apache_commons_commons_csv' //salsah1/src/test/scala/org.knora.salsah/browser:InternationalizationSpec
buildozer 'remove deps @maven//:com_fasterxml_jackson_core_jackson_databind' //salsah1/src/test/scala/org.knora.salsah/browser:InternationalizationSpec
buildozer 'remove deps @io_bazel_rules_scala//scala/scalatest:scalatest' //salsah1/src/test/scala/org.knora.salsah/browser:InternationalizationSpec
buildozer 'remove deps @maven//:io_netty_netty_handler' //salsah1/src/test/scala/org.knora.salsah/browser:InternationalizationSpec
buildozer 'remove deps @maven//:com_typesafe_akka_akka_protobuf_2_12' //salsah1/src/test/scala/org.knora.salsah/browser:InternationalizationSpec
buildozer 'remove deps @maven//:org_eclipse_rdf4j_rdf4j_repository_event' //salsah1/src/test/scala/org.knora.salsah/browser:InternationalizationSpec
buildozer 'remove deps @maven//:org_json4s_json4s_core_2_12' //salsah1/src/test/scala/org.knora.salsah/browser:InternationalizationSpec
buildozer 'remove deps @maven//:joda_time_joda_time' //salsah1/src/test/scala/org.knora.salsah/browser:InternationalizationSpec
buildozer 'remove deps @maven//:org_locationtech_jts_jts_core' //salsah1/src/test/scala/org.knora.salsah/browser:InternationalizationSpec
buildozer 'remove deps @maven//:org_typelevel_cats_macros_2_12' //salsah1/src/test/scala/org.knora.salsah/browser:InternationalizationSpec
buildozer 'remove deps @maven//:io_gatling_gatling_redis' //salsah1/src/test/scala/org.knora.salsah/browser:InternationalizationSpec
buildozer 'remove deps @maven//:com_pauldijou_jwt_json_common_2_12' //salsah1/src/test/scala/org.knora.salsah/browser:InternationalizationSpec
buildozer 'remove deps @maven//:com_fasterxml_jackson_core_jackson_core' //salsah1/src/test/scala/org.knora.salsah/browser:InternationalizationSpec
buildozer 'remove deps @maven//:com_typesafe_akka_akka_http_testkit_2_12' //salsah1/src/test/scala/org.knora.salsah/browser:InternationalizationSpec
buildozer 'remove deps @maven//:org_apache_lucene_lucene_memory' //salsah1/src/test/scala/org.knora.salsah/browser:InternationalizationSpec
buildozer 'remove deps @maven//:org_eclipse_rdf4j_rdf4j_sail_spin' //salsah1/src/test/scala/org.knora.salsah/browser:InternationalizationSpec
buildozer 'remove deps @maven//:com_github_scopt_scopt_2_12' //salsah1/src/test/scala/org.knora.salsah/browser:InternationalizationSpec
buildozer 'remove deps @maven//:com_typesafe_ssl_config_core_2_12' //salsah1/src/test/scala/org.knora.salsah/browser:InternationalizationSpec
buildozer 'remove deps @maven//:com_softwaremill_quicklens_quicklens_2_12' //salsah1/src/test/scala/org.knora.salsah/browser:InternationalizationSpec
buildozer 'remove deps @maven//:org_apache_jena_jena_base' //salsah1/src/test/scala/org.knora.salsah/browser:InternationalizationSpec
buildozer 'remove deps @maven//:org_simpleflatmapper_lightning_csv' //salsah1/src/test/scala/org.knora.salsah/browser:InternationalizationSpec
buildozer 'remove deps @maven//:org_eclipse_rdf4j_rdf4j_repository_http' //salsah1/src/test/scala/org.knora.salsah/browser:InternationalizationSpec
buildozer 'remove deps @maven//:org_eclipse_rdf4j_rdf4j_http_client' //salsah1/src/test/scala/org.knora.salsah/browser:InternationalizationSpec
buildozer 'remove deps @maven//:org_eclipse_rdf4j_rdf4j_rio_rdfxml' //salsah1/src/test/scala/org.knora.salsah/browser:InternationalizationSpec
buildozer 'remove deps @maven//:org_eclipse_rdf4j_rdf4j_sail_api' //salsah1/src/test/scala/org.knora.salsah/browser:InternationalizationSpec
buildozer 'remove deps @maven//:org_bouncycastle_bcpkix_jdk15on' //salsah1/src/test/scala/org.knora.salsah/browser:InternationalizationSpec
buildozer 'remove deps @maven//:commons_validator_commons_validator' //salsah1/src/test/scala/org.knora.salsah/browser:InternationalizationSpec
