buildozer 'remove deps @maven//:com_typesafe_akka_akka_slf4j_2_12' //webapi:it_library
buildozer 'remove deps @maven//:commons_io_commons_io' //webapi:test_library
buildozer 'remove deps @maven//:ch_qos_logback_logback_core' //webapi:test_library
buildozer 'remove deps @maven//:xml_apis_xml_apis' //webapi:test_library
buildozer 'remove deps @maven//:com_typesafe_akka_akka_slf4j_2_12' //webapi:test_library
buildozer 'remove deps @maven//:org_xmlunit_xmlunit_core' //webapi:test_library
buildozer 'remove deps @maven//:com_typesafe_play_twirl_api_2_12' //webapi:test_library
buildozer 'remove deps @maven//:org_springframework_security_spring_security_core' //webapi:test_library
buildozer 'remove deps @maven//:commons_validator_commons_validator' //webapi:test_library
buildozer 'remove deps @maven//:org_eclipse_rdf4j_rdf4j_model' //webapi:test_library
buildozer 'remove deps @maven//:org_eclipse_rdf4j_rdf4j_rio_api' //webapi:test_library
buildozer 'remove deps @maven//:ch_qos_logback_logback_classic' //webapi:test_library
buildozer 'remove deps @maven//:org_scala_lang_modules_scala_xml_2_12' //webapi:test_library
buildozer 'remove deps @maven//:ch_megard_akka_http_cors_2_12' //webapi:test_library
buildozer 'remove deps @maven//:com_typesafe_akka_akka_actor_2_12' //webapi/src/test/scala/org/knora/webapi/responders:IriLockerSpec
buildozer 'remove deps @maven//:com_typesafe_config' //webapi/src/test/scala/org/knora/webapi/responders:IriLockerSpec
buildozer 'remove deps //webapi:test_library' //webapi/src/test/scala/org/knora/webapi/responders:IriLockerSpec
buildozer 'remove deps @maven//:com_typesafe_scala_logging_scala_logging_2_12' //webapi/src/test/scala/org/knora/webapi/responders:IriLockerSpec
buildozer 'remove deps @maven//:io_spray_spray_json_2_12' //webapi/src/test/scala/org/knora/webapi/responders:IriLockerSpec
buildozer 'remove deps @maven//:com_typesafe_akka_akka_stream_2_12' //webapi/src/test/scala/org/knora/webapi/responders:IriLockerSpec
buildozer 'remove deps @maven//:com_typesafe_akka_akka_http_spray_json_2_12' //webapi/src/test/scala/org/knora/webapi/responders:IriLockerSpec
buildozer 'remove deps @maven//:com_typesafe_akka_akka_testkit_2_12' //webapi/src/test/scala/org/knora/webapi/responders:IriLockerSpec
buildozer 'remove deps @maven//:com_typesafe_akka_akka_slf4j_2_12' //webapi/src/it/scala/org/knora/webapi:KnoraSipiIntegrationV2ITSpec
buildozer 'remove deps @maven//:com_typesafe_akka_akka_testkit_2_12' //webapi/src/test/scala/org/knora/webapi/util:DateUtilV1Spec
buildozer 'remove deps @maven//:org_xmlunit_xmlunit_core' //webapi/src/test/scala/org/knora/webapi/util:DateUtilV1Spec
buildozer 'remove deps @maven//:io_spray_spray_json_2_12' //webapi/src/test/scala/org/knora/webapi/util:DateUtilV1Spec
buildozer 'remove deps @maven//:com_typesafe_akka_akka_actor_2_12' //webapi/src/test/scala/org/knora/webapi/util:DateUtilV1Spec
buildozer 'remove deps //webapi:test_library' //webapi/src/test/scala/org/knora/webapi/util:DateUtilV1Spec
buildozer 'remove deps @maven//:com_typesafe_akka_akka_stream_2_12' //webapi/src/test/scala/org/knora/webapi/util:DateUtilV1Spec
buildozer 'remove deps @maven//:com_typesafe_scala_logging_scala_logging_2_12' //webapi/src/test/scala/org/knora/webapi/util:DateUtilV1Spec
buildozer 'remove deps @maven//:com_typesafe_config' //webapi/src/test/scala/org/knora/webapi/util:DateUtilV1Spec
buildozer 'remove deps @maven//:com_typesafe_akka_akka_http_spray_json_2_12' //webapi/src/test/scala/org/knora/webapi/util:DateUtilV1Spec
buildozer 'remove deps @maven//:org_xmlunit_xmlunit_core' //webapi/src/test/scala/org/knora/webapi/util:GenerateContributorsFileSpec
buildozer 'remove deps @maven//:com_typesafe_akka_akka_http_spray_json_2_12' //webapi/src/test/scala/org/knora/webapi/util:GenerateContributorsFileSpec
buildozer 'remove deps @maven//:io_spray_spray_json_2_12' //webapi/src/test/scala/org/knora/webapi/util:GenerateContributorsFileSpec
buildozer 'remove deps @maven//:org_xmlunit_xmlunit_core' //webapi/src/test/scala/org/knora/webapi/util:CacheUtilSpec
buildozer 'remove deps @maven//:com_typesafe_akka_akka_http_spray_json_2_12' //webapi/src/test/scala/org/knora/webapi/util:CacheUtilSpec
buildozer 'remove deps @maven//:io_spray_spray_json_2_12' //webapi/src/test/scala/org/knora/webapi/util:CacheUtilSpec
buildozer 'remove deps @maven//:com_typesafe_akka_akka_http_core_2_12' //webapi/src/test/scala/org/knora/webapi/responders/v1:ProjectsResponderV1Spec
buildozer 'remove deps @maven//:com_typesafe_akka_akka_http_2_12' //webapi/src/test/scala/org/knora/webapi/responders/v1:ProjectsResponderV1Spec
buildozer 'remove deps @maven//:com_typesafe_akka_akka_http_spray_json_2_12' //webapi/src/test/scala/org/knora/webapi/responders/v1:OntologyResponderV1Spec
buildozer 'remove deps @maven//:io_spray_spray_json_2_12' //webapi/src/test/scala/org/knora/webapi/responders/v1:OntologyResponderV1Spec
buildozer 'remove deps @maven//:com_typesafe_akka_akka_http_spray_json_2_12' //webapi/src/test/scala/org/knora/webapi/responders/v2/search:GravsearchTypeInspectorSpec
buildozer 'remove deps @maven//:io_spray_spray_json_2_12' //webapi/src/test/scala/org/knora/webapi/responders/v2/search:GravsearchTypeInspectorSpec
buildozer 'remove deps @maven//:com_typesafe_akka_akka_http_spray_json_2_12' //webapi/src/test/scala/org/knora/webapi/store/triplestore:GraphDBConsistencyCheckingSpec
buildozer 'remove deps @maven//:io_spray_spray_json_2_12' //webapi/src/test/scala/org/knora/webapi/store/triplestore:GraphDBConsistencyCheckingSpec
buildozer 'remove deps @maven//:org_xmlunit_xmlunit_core' //webapi/src/test/scala/org/knora/webapi/util:StringLiteralSequenceV2Spec
buildozer 'remove deps @maven//:com_typesafe_akka_akka_http_spray_json_2_12' //webapi/src/test/scala/org/knora/webapi/util:StringLiteralSequenceV2Spec
buildozer 'remove deps @maven//:io_spray_spray_json_2_12' //webapi/src/test/scala/org/knora/webapi/util:StringLiteralSequenceV2Spec
buildozer 'remove deps @maven//:com_typesafe_akka_akka_http_spray_json_2_12' //webapi/src/test/scala/org/knora/webapi/store/triplestore:AllTriplestoreSpec
buildozer 'remove deps @maven//:io_spray_spray_json_2_12' //webapi/src/test/scala/org/knora/webapi/store/triplestore:AllTriplestoreSpec
buildozer 'remove deps @maven//:org_xmlunit_xmlunit_core' //webapi/src/test/scala/org/knora/webapi/util:PermissionUtilADMSpec
buildozer 'remove deps @maven//:com_typesafe_akka_akka_http_core_2_12' //webapi/src/test/scala/org/knora/webapi/responders/v2/search:NonTriplestoreSpecificGravsearchToPrequeryGeneratorSpec
buildozer 'remove deps @maven//:com_typesafe_akka_akka_http_spray_json_2_12' //webapi/src/test/scala/org/knora/webapi/responders/v2/search:NonTriplestoreSpecificGravsearchToPrequeryGeneratorSpec
buildozer 'remove deps @maven//:io_spray_spray_json_2_12' //webapi/src/test/scala/org/knora/webapi/responders/v2/search:NonTriplestoreSpecificGravsearchToPrequeryGeneratorSpec
buildozer 'remove deps @maven//:com_typesafe_akka_akka_http_2_12' //webapi/src/test/scala/org/knora/webapi/responders/v2/search:NonTriplestoreSpecificGravsearchToPrequeryGeneratorSpec
buildozer 'remove deps @maven//:com_typesafe_akka_akka_http_spray_json_2_12' //webapi/src/test/scala/org/knora/webapi/routing:AuthenticatorSpec
buildozer 'remove deps @maven//:com_typesafe_akka_akka_http_core_2_12' //webapi/src/test/scala/org/knora/webapi/responders/v1:ValuesResponderV1Spec
buildozer 'remove deps @maven//:com_typesafe_akka_akka_http_spray_json_2_12' //webapi/src/test/scala/org/knora/webapi/store/cacheservice:CacheServiceManagerSpec
buildozer 'remove deps @maven//:io_spray_spray_json_2_12' //webapi/src/test/scala/org/knora/webapi/store/cacheservice:CacheServiceManagerSpec
buildozer 'remove deps @maven//:org_slf4j_slf4j_api' //webapi/src/it/scala/org/knora/webapi:VersionRouteITSpec
buildozer 'remove deps @maven//:com_typesafe_akka_akka_slf4j_2_12' //webapi/src/it/scala/org/knora/webapi:VersionRouteITSpec
buildozer 'remove deps @maven//:com_typesafe_akka_akka_http_core_2_12' //webapi/src/test/scala/org/knora/webapi/responders/v1:UsersResponderV1Spec
buildozer 'remove deps @maven//:com_typesafe_akka_akka_http_spray_json_2_12' //webapi/src/test/scala/org/knora/webapi/responders/v1:UsersResponderV1Spec
buildozer 'remove deps @maven//:io_spray_spray_json_2_12' //webapi/src/test/scala/org/knora/webapi/responders/v1:UsersResponderV1Spec
buildozer 'remove deps @maven//:com_typesafe_akka_akka_http_2_12' //webapi/src/test/scala/org/knora/webapi/responders/v1:UsersResponderV1Spec
buildozer 'remove deps @maven//:com_typesafe_akka_akka_http_core_2_12' //webapi/src/test/scala/org/knora/webapi/responders/v2:ValuesResponderV2Spec
buildozer 'remove deps @maven//:com_typesafe_akka_akka_slf4j_2_12' //webapi/src/it/scala/org/knora/webapi:ErrorV1ITSpec
buildozer 'remove deps @maven//:com_typesafe_akka_akka_http_spray_json_2_12' //webapi/src/test/scala/org/knora/webapi/util/jsonld:JsonLDUtilSpec
buildozer 'remove deps @maven//:org_xmlunit_xmlunit_core' //webapi/src/test/scala/org/knora/webapi/util:StringFormatterSpec
buildozer 'remove deps @maven//:com_typesafe_akka_akka_http_spray_json_2_12' //webapi/src/test/scala/org/knora/webapi/util:StringFormatterSpec
buildozer 'remove deps @maven//:io_spray_spray_json_2_12' //webapi/src/test/scala/org/knora/webapi/util:StringFormatterSpec
buildozer 'remove deps @maven//:com_typesafe_akka_akka_http_spray_json_2_12' //webapi/src/test/scala/org/knora/webapi/util/clientapi:SourceCodeFilePathSpec
buildozer 'remove deps @maven//:io_spray_spray_json_2_12' //webapi/src/test/scala/org/knora/webapi/util/clientapi:SourceCodeFilePathSpec
buildozer 'remove deps @maven//:org_xmlunit_xmlunit_core' //webapi/src/test/scala/org/knora/webapi/util:ApacheLuceneSupportSpec
buildozer 'remove deps @maven//:com_typesafe_akka_akka_http_spray_json_2_12' //webapi/src/test/scala/org/knora/webapi/util:ApacheLuceneSupportSpec
buildozer 'remove deps @maven//:io_spray_spray_json_2_12' //webapi/src/test/scala/org/knora/webapi/util:ApacheLuceneSupportSpec
buildozer 'remove deps @maven//:com_typesafe_akka_akka_slf4j_2_12' //webapi/src/it/scala/org/knora/webapi:KnoraSipiPermissionsV1ITSpec
buildozer 'remove deps @maven//:com_typesafe_akka_akka_http_spray_json_2_12' //webapi/src/test/scala/org/knora/webapi/responders/v2:OntologyResponderV2Spec
buildozer 'remove deps @maven//:io_spray_spray_json_2_12' //webapi/src/test/scala/org/knora/webapi/responders/v2:OntologyResponderV2Spec
buildozer 'remove deps @maven//:com_typesafe_akka_akka_http_spray_json_2_12' //webapi/src/test/scala/org/knora/webapi/store/cacheservice:CacheSerializationSpec
buildozer 'remove deps @maven//:io_spray_spray_json_2_12' //webapi/src/test/scala/org/knora/webapi/store/cacheservice:CacheSerializationSpec
buildozer 'remove deps @maven//:org_xmlunit_xmlunit_core' //webapi/src/test/scala/org/knora/webapi:SettingsSpec
buildozer 'remove deps @maven//:com_typesafe_akka_akka_http_spray_json_2_12' //webapi/src/test/scala/org/knora/webapi:SettingsSpec
buildozer 'remove deps @maven//:io_spray_spray_json_2_12' //webapi/src/test/scala/org/knora/webapi:SettingsSpec
buildozer 'remove deps @maven//:com_typesafe_akka_akka_http_spray_json_2_12' //webapi/src/test/scala/org/knora/webapi/util/standoff:StandoffTagUtilV2Spec
buildozer 'remove deps @maven//:io_spray_spray_json_2_12' //webapi/src/test/scala/org/knora/webapi/util/standoff:StandoffTagUtilV2Spec
buildozer 'remove deps @maven//:org_slf4j_slf4j_api' //webapi/src/it/scala/org/knora/webapi:KnoraSipiIntegrationV1ITSpec
buildozer 'remove deps @maven//:com_typesafe_akka_akka_slf4j_2_12' //webapi/src/it/scala/org/knora/webapi:KnoraSipiIntegrationV1ITSpec
buildozer 'remove deps @maven//:com_typesafe_akka_akka_http_core_2_12' //webapi/src/test/scala/org/knora/webapi/responders/v2:ResourcesResponseCheckerV2Spec
buildozer 'remove deps @maven//:com_typesafe_akka_akka_http_spray_json_2_12' //webapi/src/test/scala/org/knora/webapi/responders/v2:ResourcesResponseCheckerV2Spec
buildozer 'remove deps @maven//:io_spray_spray_json_2_12' //webapi/src/test/scala/org/knora/webapi/responders/v2:ResourcesResponseCheckerV2Spec
buildozer 'remove deps @maven//:com_typesafe_akka_akka_http_2_12' //webapi/src/test/scala/org/knora/webapi/responders/v2:ResourcesResponseCheckerV2Spec
buildozer 'remove deps @maven//:com_typesafe_akka_akka_http_spray_json_2_12' //webapi/src/test/scala/org/knora/webapi/util/date:CalendarDateUtilV2Spec
buildozer 'remove deps @maven//:io_spray_spray_json_2_12' //webapi/src/test/scala/org/knora/webapi/util/date:CalendarDateUtilV2Spec
buildozer 'remove deps @maven//:com_typesafe_akka_akka_http_core_2_12' //webapi/src/test/scala/org/knora/webapi/responders/v2:ResourcesResponderV2Spec
buildozer 'remove deps @maven//:com_typesafe_akka_akka_http_spray_json_2_12' //webapi/src/test/scala/org/knora/webapi/responders/v2:ResourcesResponderV2Spec
buildozer 'remove deps @maven//:io_spray_spray_json_2_12' //webapi/src/test/scala/org/knora/webapi/responders/v2:ResourcesResponderV2Spec
buildozer 'remove deps @maven//:com_typesafe_akka_akka_http_spray_json_2_12' //webapi/src/test/scala/org/knora/webapi/routing:JWTHelperSpec
buildozer 'remove deps @maven//:com_typesafe_akka_akka_http_spray_json_2_12' //webapi/src/test/scala/org/knora/webapi/util/clientapi:ClientCollectionTypeParserSpec
buildozer 'remove deps @maven//:io_spray_spray_json_2_12' //webapi/src/test/scala/org/knora/webapi/util/clientapi:ClientCollectionTypeParserSpec
buildozer 'remove deps @maven//:com_typesafe_akka_akka_testkit_2_12' //webapi/src/test/scala/org/knora/webapi/responders/v2/search:GravsearchParserSpec
buildozer 'remove deps //webapi:test_library' //webapi/src/test/scala/org/knora/webapi/responders/v2/search:GravsearchParserSpec
buildozer 'remove deps @maven//:com_typesafe_config' //webapi/src/test/scala/org/knora/webapi/responders/v2/search:GravsearchParserSpec
buildozer 'remove deps @maven//:com_typesafe_akka_akka_actor_2_12' //webapi/src/test/scala/org/knora/webapi/responders/v2/search:GravsearchParserSpec
buildozer 'remove deps @maven//:com_typesafe_akka_akka_stream_2_12' //webapi/src/test/scala/org/knora/webapi/responders/v2/search:GravsearchParserSpec
buildozer 'remove deps @maven//:com_typesafe_scala_logging_scala_logging_2_12' //webapi/src/test/scala/org/knora/webapi/responders/v2/search:GravsearchParserSpec
buildozer 'remove deps @maven//:org_slf4j_slf4j_api' //webapi/src/it/scala/org/knora/webapi:DrawingsGodsV1ITSpec
buildozer 'remove deps @maven//:com_typesafe_akka_akka_slf4j_2_12' //webapi/src/it/scala/org/knora/webapi:DrawingsGodsV1ITSpec
buildozer 'remove deps @maven//:com_typesafe_akka_akka_http_spray_json_2_12' //webapi/src/test/scala/org/knora/webapi/util/standoff:XMLToStandoffUtilSpec
buildozer 'remove deps @maven//:io_spray_spray_json_2_12' //webapi/src/test/scala/org/knora/webapi/util/standoff:XMLToStandoffUtilSpec
buildozer 'remove deps @maven//:com_typesafe_akka_akka_http_spray_json_2_12' //webapi/src/test/scala/org/knora/webapi/responders/v2/search:NonTriplestoreSpecificGravsearchToCountPrequeryGeneratorSpec
buildozer 'remove deps @maven//:io_spray_spray_json_2_12' //webapi/src/test/scala/org/knora/webapi/responders/v2/search:NonTriplestoreSpecificGravsearchToCountPrequeryGeneratorSpec
buildozer 'remove deps @maven//:com_typesafe_scala_logging_scala_logging_2_12' //webapi/src/it/scala/org/knora/webapi:KnoraSipiScriptsV1ITSpec
buildozer 'remove deps @maven//:com_typesafe_akka_akka_slf4j_2_12' //webapi/src/it/scala/org/knora/webapi:KnoraSipiScriptsV1ITSpec
buildozer 'remove deps @maven//:com_typesafe_akka_akka_http_spray_json_2_12' //webapi/src/test/scala/org/knora/webapi/responders/v2:ListsResponderV2Spec
buildozer 'remove deps @maven//:io_spray_spray_json_2_12' //webapi/src/test/scala/org/knora/webapi/responders/v2:ListsResponderV2Spec
buildozer 'remove deps @maven//:com_typesafe_akka_akka_http_spray_json_2_12' //webapi/src/test/scala/org/knora/webapi/util/standoff:XMLUtilSpec
buildozer 'remove deps @maven//:io_spray_spray_json_2_12' //webapi/src/test/scala/org/knora/webapi/util/standoff:XMLUtilSpec
buildozer 'remove deps @maven//:org_xmlunit_xmlunit_core' //webapi/src/test/scala/org/knora/webapi/util:Base64UrlCheckDigitSpec
buildozer 'remove deps @maven//:com_typesafe_akka_akka_http_spray_json_2_12' //webapi/src/test/scala/org/knora/webapi/util:Base64UrlCheckDigitSpec
buildozer 'remove deps @maven//:io_spray_spray_json_2_12' //webapi/src/test/scala/org/knora/webapi/util:Base64UrlCheckDigitSpec
