buildozer 'remove deps //tools/version_info:version_info' //webapi/src/test/scala/org/knora/webapi/messages/admin/responder/permissionsmessages:PermissionsMessagesADMSpec
buildozer 'remove deps //webapi/src/main/scala/org/knora/webapi/app:app' //webapi/src/test/scala/org/knora/webapi/messages/admin/responder/permissionsmessages:PermissionsMessagesADMSpec
buildozer 'remove deps //webapi/src/main/scala/org/knora/webapi/core:core' //webapi/src/test/scala/org/knora/webapi/messages/admin/responder/permissionsmessages:PermissionsMessagesADMSpec
buildozer 'remove deps //webapi/src/main/scala/org/knora/webapi/exceptions:exceptions' //webapi/src/test/scala/org/knora/webapi/messages/admin/responder/permissionsmessages:PermissionsMessagesADMSpec
buildozer 'remove deps //webapi/src/main/scala/org/knora/webapi/http/handler:handler' //webapi/src/test/scala/org/knora/webapi/messages/admin/responder/permissionsmessages:PermissionsMessagesADMSpec
buildozer 'remove deps //webapi/src/main/scala/org/knora/webapi/http/version:version' //webapi/src/test/scala/org/knora/webapi/messages/admin/responder/permissionsmessages:PermissionsMessagesADMSpec
buildozer 'remove deps //webapi/src/main/scala/org/knora/webapi/instrumentation:instrumentation' //webapi/src/test/scala/org/knora/webapi/messages/admin/responder/permissionsmessages:PermissionsMessagesADMSpec
buildozer 'remove deps //webapi/src/main/scala/org/knora/webapi/responders:responders' //webapi/src/test/scala/org/knora/webapi/messages/admin/responder/permissionsmessages:PermissionsMessagesADMSpec
buildozer 'remove deps //webapi/src/main/scala/org/knora/webapi/routing:routing' //webapi/src/test/scala/org/knora/webapi/messages/admin/responder/permissionsmessages:PermissionsMessagesADMSpec
buildozer 'remove deps //webapi/src/main/scala/org/knora/webapi/settings:settings' //webapi/src/test/scala/org/knora/webapi/messages/admin/responder/permissionsmessages:PermissionsMessagesADMSpec
buildozer 'remove deps //webapi/src/main/scala/org/knora/webapi/store:store' //webapi/src/test/scala/org/knora/webapi/messages/admin/responder/permissionsmessages:PermissionsMessagesADMSpec
buildozer 'remove deps //webapi/src/main/scala/org/knora/webapi/util:util' //webapi/src/test/scala/org/knora/webapi/messages/admin/responder/permissionsmessages:PermissionsMessagesADMSpec
buildozer 'remove deps //webapi/src/main/scala/org/knora/webapi/util/cache:cache' //webapi/src/test/scala/org/knora/webapi/messages/admin/responder/permissionsmessages:PermissionsMessagesADMSpec
buildozer 'remove deps //webapi:main_library' //webapi/src/test/scala/org/knora/webapi/messages/admin/responder/permissionsmessages:PermissionsMessagesADMSpec
