SELECT DISTINCT ?mainRes (GROUP_CONCAT(DISTINCT(IF(BOUND(?v), STR(?v), "")); SEPARATOR='') AS ?v__Concat)
WHERE {
?mainRes <http://www.knora.org/ontology/knora-base#attachedToProject> <http://rdfh.ch/projects/0102> .
VALUES ?mainRes__resTypes { <http://www.knora.org/ontology/0102/scenario-tanner#Correspondence> <http://www.knora.org/ontology/0102/scenario-tanner#CriticalReception> <http://www.knora.org/ontology/0102/scenario-tanner#Document> <http://www.knora.org/ontology/0102/scenario-tanner#InterviewArchive> <http://www.knora.org/ontology/0102/scenario-tanner#Production> <http://www.knora.org/ontology/0102/scenario-tanner#Promotion> <http://www.knora.org/ontology/0102/scenario-tanner#Script> }
?mainRes <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?mainRes__resTypes .
?mainRes <http://www.w3.org/2000/01/rdf-schema#label> ?l .
?mainRes <http://www.knora.org/ontology/0102/scenario-tanner#hasShelfNumber> ?v .
?v <http://www.knora.org/ontology/knora-base#valueHasString> ?s .
FILTER((?s = "CH_CS_CSL-020-01-08-01-01"^^<http://www.w3.org/2001/XMLSchema#string>))
FILTER NOT EXISTS {
 ?mainRes <http://www.knora.org/ontology/knora-base#isDeleted> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .

}
FILTER NOT EXISTS {
 ?v <http://www.knora.org/ontology/knora-base#isDeleted> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .

}
}
GROUP BY ?mainRes
ORDER BY ASC(?mainRes)
LIMIT 25
