SELECT DISTINCT ?mainRes
WHERE {
?mainRes <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.knora.org/ontology/0812/ekws#Object> .
?mainRes <http://www.knora.org/ontology/0812/ekws#hasConcept> <http://rdfh.ch/0812/HF06nlmuSyyOIkqLCgeF7Q> .
?mainRes <http://www.knora.org/ontology/0812/ekws#hasConceptValue> ?lv .
?lv <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.knora.org/ontology/knora-base#LinkValue> .
?lv <http://www.w3.org/1999/02/22-rdf-syntax-ns#object> <http://rdfh.ch/0812/HF06nlmuSyyOIkqLCgeF7Q> .
FILTER NOT EXISTS {
 ?mainRes <http://www.knora.org/ontology/knora-base#isDeleted> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .

}
FILTER NOT EXISTS {
 ?lv <http://www.knora.org/ontology/knora-base#isDeleted> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .

}
FILTER NOT EXISTS {
 <http://rdfh.ch/0812/HF06nlmuSyyOIkqLCgeF7Q> <http://www.knora.org/ontology/knora-base#isDeleted> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .

}
}
GROUP BY ?mainRes
ORDER BY ASC(?mainRes)
LIMIT 25
