/*
 * Copyright © 2015-2018 the contributors (see Contributors.md).
 *
 *  This file is part of Knora.
 *
 *  Knora is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as published
 *  by the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Knora is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public
 *  License along with Knora.  If not, see <http://www.gnu.org/licenses/>.
 */

package org.knora.webapi

import scala.Predef._

/** This object was generated by //tools/buildstamp:version.bzl. */
case object BuildInfo {

    val name: String = "webapi"

    val version: String = "{BUILD_SCM_TAG}"

    val scalaVersion: String = "2.12.8"

    val sbtVersion: String = "1.2.8"

    val akkaHttp: String = "{AKKA_HTTP_VERSION}"

    val sipiVersion: String = "{SIPI_VERSION}"

    override val toString: String = {
        "name: %s, version: %s, scalaVersion: %s, sbtVersion: %s, akkaHttp: %s".format(
            name, version, scalaVersion, sbtVersion, akkaHttp, sipiVersion
        )
    }
}