site_name: Dsp-Ingest

nav:
  - OpenAPI Documentation: openapi.md
  - Introduction: index.md
  - Ingesting Assets: ingest.md
  - Authentication: authentication.md
  - Service documentation:
      - Configuration: service-configuration.md
      - Filesystem Setup: service-filesystem-setup.md

plugins:
  - include-markdown
  - search
  - git-revision-date-localized

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
