package(default_visibility = ["//visibility:public"])

filegroup(
    name = "knora-ontologies",
    srcs = [
        "knora-admin.ttl",
        "knora-base.ttl",
        "salsah-gui.ttl",
        "standoff-data.ttl",
        "standoff-onto.ttl",
    ],
)