/*
 * Copyright © 2022 Swiss National Data and Service Center for the Humanities and/or DaSCH Service Platform contributors.
 * SPDX-License-Identifier: Apache-2.0
 */

package org.knora.webapi.http.version.versioninfo

/** This object was generated by //tools/version_info. */
case object VersionInfo {

  val name: String = "webapi"

  val webapiVersion: String = "{BUILD_TAG}"

  val scalaVersion: String = "{SCALA_VERSION}"

  val akkaHttpVersion: String = "{AKKA_HTTP_VERSION}"

  val sipiVersion: String = "{SIPI_VERSION}"

  val jenaFusekiVersion = "{FUSEKI_VERSION}"

  override val toString: String = {
    "name: %s, version: %s, scalaVersion: %s, akkaHttpVersion: %s, sipiVersion: %s, jenaFusekiVersion: %s".format(
      name,
      webapiVersion,
      scalaVersion,
      akkaHttpVersion,
      sipiVersion,
      jenaFusekiVersion
    )
  }
}
