addSbtPlugin("com.eed3si9n"      % "sbt-buildinfo"       % "0.13.1")
addSbtPlugin("com.github.sbt"    % "sbt-native-packager" % "1.11.0")
addSbtPlugin("de.heikoseeberger" % "sbt-header"          % "5.10.0")
addSbtPlugin("org.typelevel"     % "sbt-tpolecat"        % "0.5.2")
addSbtPlugin("io.spray"          % "sbt-revolver"        % "0.10.0")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt"        % "2.5.3")
addSbtPlugin("org.scoverage"     % "sbt-scoverage"       % "2.3.0")
