addSbtPlugin("com.eed3si9n"      % "sbt-buildinfo"       % "0.11.0")
addSbtPlugin("com.github.sbt"    % "sbt-native-packager" % "1.9.16")
addSbtPlugin("de.heikoseeberger" % "sbt-header"          % "5.10.0")
addSbtPlugin("org.typelevel"     % "sbt-tpolecat"        % "0.5.0")
addSbtPlugin("io.spray"          % "sbt-revolver"        % "0.10.0")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt"        % "2.5.2")
addSbtPlugin("org.scoverage"     % "sbt-scoverage"       % "2.0.8")
