addSbtPlugin("com.github.sbt"            % "sbt-native-packager" % "1.9.16")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"        % "0.4.2")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"        % "2.5.0")
addSbtPlugin("de.heikoseeberger"         % "sbt-header"          % "5.9.0")
addSbtPlugin("com.eed3si9n"              % "sbt-buildinfo"       % "0.11.0")
