"""Generate a BuildInfo.scala object, replacing sbt-buildinfo.

`string_fields` are baked in verbatim. `stamp_fields` map a Scala val name to a
workspace-status key (see tools/workspace_status.sh); their values are read from
the stable-status file at action time, so a version change recompiles only the
tiny generated library, not the world.
"""

def _buildinfo_impl(ctx):
    out = ctx.actions.declare_file(ctx.attr.out)
    tmpl = ctx.actions.declare_file(ctx.attr.out + ".in")

    lines = [
        "package " + ctx.attr.package_name,
        "",
        "// Generated by //tools/buildinfo — do not edit.",
        "object BuildInfo {",
    ]
    for k in ctx.attr.string_fields:
        lines.append('  val %s: String = "%s"' % (k, ctx.attr.string_fields[k]))
    for k in ctx.attr.stamp_fields:
        lines.append('  val %s: String = "__%s__"' % (k, ctx.attr.stamp_fields[k]))
    lines.append("}")
    lines.append("")
    ctx.actions.write(tmpl, "\n".join(lines))

    info = ctx.info_file  # bazel-out/stable-status.txt (from workspace_status_command)

    # Unique stamp keys → substitute their status values.
    keys = {ctx.attr.stamp_fields[k]: True for k in ctx.attr.stamp_fields}
    script = "set -euo pipefail\ncp %s %s\n" % (tmpl.path, out.path)
    for key in keys:
        script += "V=\"$(grep '^%s ' %s | cut -d' ' -f2- || true)\"\n" % (key, info.path)
        script += 'sed "s|__%s__|$V|g" %s > %s.n && mv %s.n %s\n' % (key, out.path, out.path, out.path, out.path)

    ctx.actions.run_shell(
        inputs = [tmpl, info],
        outputs = [out],
        command = script,
        mnemonic = "BuildInfoGen",
        progress_message = "Generating %s" % out.short_path,
    )
    return [DefaultInfo(files = depset([out]))]

buildinfo = rule(
    implementation = _buildinfo_impl,
    attrs = {
        "package_name": attr.string(mandatory = True),
        "out": attr.string(mandatory = True, doc = "Output .scala file name"),
        "string_fields": attr.string_dict(doc = "val name -> literal string"),
        "stamp_fields": attr.string_dict(doc = "val name -> workspace-status key"),
    },
)
