services:
  ingest:
    image: daschswiss/dsp-ingest:latest
    ports:
      - "3340:3340"
    volumes:
      - ./localdev/storage/images:/opt/images:delegated
      - ./localdev/storage/temp:/opt/temp:delegated
      - ./localdev/storage/db:/opt/db:delegated
    environment:
      - SERVICE_HOST=0.0.0.0
      - SERVICE_PORT=3340
      - SERVICE_LOG_FORMAT=text
      - SERVICE_LOG_LEVEL=info
      - STORAGE_ASSET_DIR=/opt/images
      - STORAGE_TEMP_DIR=/opt/temp
      - JWT_AUDIENCE=http://localhost:3340
      - JWT_ISSUER=0.0.0.0:3333
      - JWT_SECRET=UP 4888, nice 4-8-4 steam engine
      - JWT_DISABLE_AUTH=true
      - INGEST_BULK_MAX_PARALLEL=10
      - SIPI_USE_LOCAL_DEV=false
      - DB_JDBC_URL=jdbc:sqlite:/opt/db/ingest.sqlite
      - DSP_API_URL=http://localhost:3333
    deploy:
      resources:
        limits:
          memory: 180MB
