PREFIX knora-base: <http://www.knora.org/ontology/knora-base#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

# Gets the IRIs and filenames of image preview files from the triplestore.

SELECT ?fileValue ?filename
FROM <http://www.ontotext.com/explicit>
WHERE {
	?fileValue a knora-base:StillImageFileValue ;
        knora-base:isPreview true ;
        knora-base:internalFilename ?filename .
}
ORDER BY ?fileValue
