package(default_visibility = ["//visibility:public"])

filegroup(
    name = "resources",
    srcs = glob(["resources/**"]),
)

filegroup(
    name = "scala",
    srcs = ["//webapi/src/test/scala/org/knora/webapi:srcs"]
)

filegroup(
    name = "java",
    srcs = glob(["java/org/knora/webapi/**/*.java"])
)

