package(default_visibility = ["//visibility:public"])

filegroup(
    name = "resources",
    srcs = glob(["resources/**"]),
)

filegroup(
    name = "scala",
    srcs = glob(["scala/org/knora/webapi/**/*.scala"])
)

filegroup(
    name = "java",
    srcs = glob(["java/org/knora/webapi/**/*.java"])
)

