package(default_visibility = ["//visibility:public"])

filegroup(
    name = "resources",
    srcs = glob(["resources/**"]),
)

filegroup(
    name = "scala",
    srcs = ["//webapi/src/it/scala/org/knora/webapi:src"]
)

