package(default_visibility = ["//visibility:public"])

filegroup(
    name = "srcs",
    srcs = ["//webapi/src/test/scala/org/knora/webapi/e2e:srcs"]
         + ["//webapi/src/test/scala/org/knora/webapi/http:srcs"]
         + ["//webapi/src/test/scala/org/knora/webapi/messages:srcs"]
         + ["//webapi/src/test/scala/org/knora/webapi/other:srcs"]
         + ["//webapi/src/test/scala/org/knora/webapi/responders:srcs"]
         + ["//webapi/src/test/scala/org/knora/webapi/routing:srcs"]
         + ["//webapi/src/test/scala/org/knora/webapi/store:srcs"]
         + ["//webapi/src/test/scala/org/knora/webapi/testing:srcs"]
         + ["//webapi/src/test/scala/org/knora/webapi/util:srcs"]
         + glob(["*.scala"])
)