name: "Preparation"
description: "Preparation steps to run tests"

inputs:
  java:
    description: "Java version to use"
    required: false
    default: "17"
runs:
  using: "composite"
  steps:
    - name: Checkout source
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up JDK ${{ inputs.java }}
      uses: actions/setup-java@v3
      with:
        distribution: "temurin"
        java-version: ${{ inputs.java }}
        cache: sbt
