package(default_visibility = ["//visibility:public"])

filegroup(
    name = "srcs",
    srcs = ["//webapi/src/test/scala/org/knora/webapi/util/clientapi:srcs"]
         + ["//webapi/src/test/scala/org/knora/webapi/util/date:srcs"]
         + ["//webapi/src/test/scala/org/knora/webapi/util/jsonld:srcs"]
         + ["//webapi/src/test/scala/org/knora/webapi/util/standoff:srcs"]
         + glob(["*.scala"])
)