PREFIX :<http://www.ontotext.com/connectors/lucene#>
PREFIX inst:<http://www.ontotext.com/connectors/lucene/instance#>
INSERT DATA {
	inst:fullTextSearch :createConnector '''
{
  "fields": [
    {
      "fieldName": "label",
      "propertyChain": [
        "http://www.w3.org/2000/01/rdf-schema#label"
      ],
      "indexed": true,
      "stored": true,
      "analyzed": true,
      "multivalued": true,
      "facet": true
    },
    {
      "fieldName": "valueHasString",
      "propertyChain": [
        "http://www.knora.org/ontology/knora-base#valueHasString"
      ],
      "indexed": true,
      "stored": true,
      "analyzed": true,
      "multivalued": true,
      "facet": true
    },
    {
      "fieldName": "valueHasComment",
      "propertyChain": [
        "http://www.knora.org/ontology/knora-base#valueHasComment"
      ],
      "indexed": true,
      "stored": true,
      "analyzed": true,
      "multivalued": true,
      "facet": true
    }
  ],
  "languages": [
    "en",
    "de",
    "fr",
    "it"
  ],
  "types": [
    "http://www.knora.org/ontology/knora-base#Resource",
    "http://www.knora.org/ontology/knora-base#Value"
  ],
  "stripMarkup": false
}
''' .
}