package(default_visibility = ["//visibility:public"])

filegroup(
    name = "all",
    srcs = [
        "//tools/build_rules:all",
        "//tools/buildstamp:all"
    ],
)

filegroup(
    name = "srcs",
    srcs = [
       "//tools/build_rules:srcs",
       "//tools/buildstamp:srcs"
    ],
)
