SELECT DISTINCT (COUNT(DISTINCT ?mainRes) AS ?count)
WHERE {
?mainRes <http://jena.apache.org/text#query> "ir14*"^^<http://www.w3.org/2001/XMLSchema#string> .
?mainRes <http://www.knora.org/ontology/knora-base#attachedToProject> <http://rdfh.ch/projects/0105> .
?mainRes <http://www.w3.org/2000/01/rdf-schema#label> ?label .
VALUES ?mainRes__resTypes { <http://www.knora.org/ontology/0105/drawings-gods#DrawingPublic> }
?mainRes <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?mainRes__resTypes .
FILTER NOT EXISTS {
 ?mainRes <http://www.knora.org/ontology/knora-base#isDeleted> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
}
}
LIMIT 1
