SELECT DISTINCT (COUNT(DISTINCT ?mainRes) AS ?count)
WHERE {
?mainRes <http://jena.apache.org/text#query> ("fortuna de ostia" 1000000) .

?mainRes <http://www.w3.org/2000/01/rdf-schema#label> ?label .
?mainRes <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?cls .
?cls <http://www.w3.org/2000/01/rdf-schema#subClassOf>* <http://www.knora.org/ontology/knora-base#Resource> .
FILTER NOT EXISTS { ?mainRes <http://www.knora.org/ontology/knora-base#isDeleted> true . }
}
LIMIT 1
