package(default_visibility = ["//visibility:public"])

filegroup(
    name = "resources",
    srcs = [
        "application.conf",
        "knoraXmlImport.xsd",
        "logback.xml",
        "mappingXMLToStandoff.xsd",
        "standoffToTEI.xsl",
        "TEIMapping.xml",
    ],
)